// +build !ignore_autogenerated

/*
Copyright 2019 The Kubernetes Authors.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlicloudMachineProviderConfig) DeepCopyInto(out *AlicloudMachineProviderConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)

	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlicloudMachineProviderConfig.
func (in *AlicloudMachineProviderConfig) DeepCopy() *AlicloudMachineProviderConfig {
	if in == nil {
		return nil
	}
	out := new(AlicloudMachineProviderConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AlicloudMachineProviderConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlicloudMachineProviderList) DeepCopyInto(out *AlicloudMachineProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AlicloudMachineProviderConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlicloudMachineProviderList.
func (in *AlicloudMachineProviderList) DeepCopy() *AlicloudMachineProviderList {
	if in == nil {
		return nil
	}
	out := new(AlicloudMachineProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AlicloudMachineProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

//// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
//func (in *AlicloudMachineProviderSpec) DeepCopyInto(out *AlicloudMachineProviderSpec) {
//	*out = *in
//	return
//}
//
//// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlicloudMachineProviderSpec.
//func (in *AlicloudMachineProviderSpec) DeepCopy() *AlicloudMachineProviderSpec {
//	if in == nil {
//		return nil
//	}
//	out := new(AlicloudMachineProviderSpec)
//	in.DeepCopyInto(out)
//	return out
//}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AlicloudMachineProviderStatus) DeepCopyInto(out *AlicloudMachineProviderStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AlicloudMachineProviderStatus.
func (in *AlicloudMachineProviderStatus) DeepCopy() *AlicloudMachineProviderStatus {
	if in == nil {
		return nil
	}
	out := new(AlicloudMachineProviderStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AlicloudMachineProviderStatus) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AliCloudMachineProviderCondition) DeepCopyInto(out *AliCloudMachineProviderCondition) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AliCloudMachineProviderCondition.
func (in *AliCloudMachineProviderCondition) DeepCopy() *AliCloudMachineProviderCondition {
	if in == nil {
		return nil
	}
	out := new(AliCloudMachineProviderCondition)
	in.DeepCopyInto(out)
	return out
}

func (in *AliCloudMachineProviderCondition) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *AliCloudMachineProviderCondition) GetObjectKind() schema.ObjectKind {
	panic("implement me")
}
