---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: cluster-api-manager-role
rules:
  - apiGroups:
      - cluster.k8s.io
    resources:
      - clusters
      - clusters/status
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - machine.openshift.io
    resources:
      - machines
      - machines/status
      - machinesets
      - machinesets/status
      - machinedeployments
      - machinedeployments/status
    verbs:
      - list
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - nodes/status
      - pods/status
    verbs:
      - patch
  - apiGroups:
      - ""
    resources:
      - pods/eviction
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - watch
      - create
      - delete
      - list
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - services
      - secrets
      - replicationcontrollers
      - persistentvolumes
      - persistentvolumeclaims
    verbs:
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - statefulsets
      - replicasets
    verbs:
      - list
      - watch
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - daemonsets
    verbs:
      - list
      - watch
      - get
  - apiGroups:
      - ""
    resources:
      - configmaps
<<<<<<< HEAD
<<<<<<< HEAD
      - secrets
=======
>>>>>>> 24c35849 (fix stop ecs instance func)
=======
      - secrets
>>>>>>> 654e3196 (add permissiong for daemonsets)
    verbs:
      - list
      - get
      - create
      - update
  - apiGroups:
<<<<<<< HEAD
<<<<<<< HEAD
      - "apps"
    resources:
      - daemonsets
=======
      - ""
    resources:
      - secrets
>>>>>>> 24c35849 (fix stop ecs instance func)
=======
      - "apps"
    resources:
      - daemonsets
>>>>>>> 654e3196 (add permissiong for daemonsets)
    verbs:
      - list
      - get
      - create
      - update
<<<<<<< HEAD
<<<<<<< HEAD
      - delete
=======
>>>>>>> 24c35849 (fix stop ecs instance func)
=======
      - delete
>>>>>>> 654e3196 (add permissiong for daemonsets)
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - watch
      - list
      - patch
