apiVersion: apps/v1
kind: Deployment
metadata:
  name: machine-api-controllers
  namespace: default
  labels:
    api: clusterapi
    k8s-app: controller
    tectonic-operators.coreos.com/managed-by: machine-api-operator
spec:
  selector:
    matchLabels:
      api: clusterapi
      k8s-app: controller
  replicas: 1
  template:
    metadata:
      labels:
        api: clusterapi
        k8s-app: controller
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        key: node.alpha.kubernetes.io/notReady
        operator: Exists
      - effect: NoExecute
        key: node.alpha.kubernetes.io/unreachable
        operator: Exists
      containers:
      - name: controller-manager
        image: registry.cn-hangzhou.aliyuncs.com/cluster-api/origin-alicloud-machine-controllers:v0.5
        command:
        - "./machine-controller-manager"
        env:
          - name: ALICLOUD_ACCESS_KEY_ID
            valueFrom:
              configMapKeyRef:
                key: ALICLOUD_ACCESS_KEY_ID
                name: my-cluster-api-config
          - name: ALICLOUD_ACCESS_KEY_SECRET
            valueFrom:
              configMapKeyRef:
                key: ALICLOUD_ACCESS_KEY_SECRET
                name: my-cluster-api-config
          - name: NODE_NAME
            valueFrom:
              configMapKeyRef:
                key: NODE_NAME
                name: my-cluster-api-config
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 30Mi

