/*
Copyright 2017 The Kubernetes Authors.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package main

import (
	"fmt"
	"github.com/AliyunContainerService/cluster-api-provider-alibabacloud/pkg/actuators/machineset"
	"github.com/aliyun/alibaba-cloud-sdk-go/services/ecs"
	"html/template"
	"os"
)

var packageTemplate = template.Must(template.New("").Parse(`/*
Copyright The Kubernetes Authors.
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// This file was generated by go generate; DO NOT EDIT
package machineset
type InstanceType struct {
	InstanceType string
	VCPU         int64
	MemoryMb     int64
	GPU          int64
}
// InstanceTypes is a map of ec2 resources
var InstanceTypes = map[string]*InstanceType{
{{- range .InstanceTypes }}
	"{{ .InstanceType }}": {
		InstanceType: "{{ .InstanceType }}",
		VCPU:         {{ .VCPU }},
		MemoryMb:     {{ .MemoryMb }},
		GPU:          {{ .GPU }},
	},
{{- end }}
}
`))

func main() {
	client, err := ecs.NewClientWithAccessKey("beijing", "<accessKeyId>", "<accessSecret>")
	request := ecs.CreateDescribeInstanceTypesRequest()
	request.Scheme = "https"
	response, err := client.DescribeInstanceTypes(request)
	if err != nil {
		fmt.Print(err.Error())
	}
	fmt.Printf("response is %#v\n", response)
	f, err := os.Create("ecs_instance_types.go")
	if err != nil {
		panic(err)
	}

	defer f.Close()
	instanceTypes := make(map[string]*machineset.InstanceType)
	for _, v := range response.InstanceTypes.InstanceType {
		instanceTypes[v.InstanceTypeId] = &machineset.InstanceType{
			InstanceType: v.InstanceType,
			VCPU:         int64(v.CpuCoreCount),
			MemoryMb:     int64(v.MemorySize * 1024),
			GPU:          int64(v.GPUAmount),
		}
		fmt.Println("get instanceType ", v.InstanceTypeId)
	}

	err = packageTemplate.Execute(f, struct {
		InstanceTypes map[string]*machineset.InstanceType
	}{
		InstanceTypes: instanceTypes,
	})

	if err != nil {
		panic(err)
	}
}
