apiVersion: v1
kind: Secret
metadata:
  name: master-user-data-secret
  namespace: default
type: Opaque
data:
  userData: |
    IyEvYmluL2Jhc2gKCmNhdCA8PEhFUkVET0MgPiAvcm9vdC91c2VyLWRhdGEuc2gKIyEvYmluL2Jh
    c2gKCmNhdCA8PEVPRiA+IC9ldGMveXVtLnJlcG9zLmQva3ViZXJuZXRlcy5yZXBvCltrdWJlcm5l
    dGVzXQpuYW1lPUt1YmVybmV0ZXMKYmFzZXVybD1odHRwczovL3BhY2thZ2VzLmNsb3VkLmdvb2ds
    ZS5jb20veXVtL3JlcG9zL2t1YmVybmV0ZXMtZWw3LXg4Nl82NAplbmFibGVkPTEKZ3BnY2hlY2s9
    MQpyZXBvX2dwZ2NoZWNrPTEKZ3Bna2V5PWh0dHBzOi8vcGFja2FnZXMuY2xvdWQuZ29vZ2xlLmNv
    bS95dW0vZG9jL3l1bS1rZXkuZ3BnIGh0dHBzOi8vcGFja2FnZXMuY2xvdWQuZ29vZ2xlLmNvbS95
    dW0vZG9jL3JwbS1wYWNrYWdlLWtleS5ncGcKZXhjbHVkZT1rdWJlKgpFT0YKc2V0ZW5mb3JjZSAw
    Cnl1bSBpbnN0YWxsIC15IGt1YmVsZXQtMS4xMy4xIGt1YmVhZG0tMS4xMy4xIGt1YmVjdGwtMS4x
    My4xIC0tZGlzYWJsZWV4Y2x1ZGVzPWt1YmVybmV0ZXMKCmNhdCA8PEVPRiA+IC9ldGMvZGVmYXVs
    dC9rdWJlbGV0CktVQkVMRVRfS1VCRUFETV9FWFRSQV9BUkdTPS0tY2dyb3VwLWRyaXZlcj1zeXN0
    ZW1kCkVPRgoKZWNobyAnMScgPiAvcHJvYy9zeXMvbmV0L2JyaWRnZS9icmlkZ2UtbmYtY2FsbC1p
    cHRhYmxlcwoKa3ViZWFkbSBpbml0IC0tYXBpc2VydmVyLWJpbmQtcG9ydCA4NDQzIC0tdG9rZW4g
    MmlxenFtLjg1YnMweDZtaXl4MW5tN2wgLS1hcGlzZXJ2ZXItY2VydC1leHRyYS1zYW5zPVwkKGN1
    cmwgLXMgaHR0cDovLzE2OS4yNTQuMTY5LjI1NC9sYXRlc3QvbWV0YS1kYXRhL3B1YmxpYy1ob3N0
    bmFtZSkgLS1hcGlzZXJ2ZXItY2VydC1leHRyYS1zYW5zPVwkKGN1cmwgLXMgaHR0cDovLzE2OS4y
    NTQuMTY5LjI1NC9sYXRlc3QvbWV0YS1kYXRhL3B1YmxpYy1pcHY0KSAtLXBvZC1uZXR3b3JrLWNp
    ZHI9MTkyLjE2OC4wLjAvMTYgLXYgNgoKIyBFbmFibGUgbmV0d29ya2luZyBieSBkZWZhdWx0Lgpr
    dWJlY3RsIGFwcGx5IC1mIGh0dHBzOi8vcmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbS9jbG91ZG5h
    dGl2ZWxhYnMva3ViZS1yb3V0ZXIvbWFzdGVyL2RhZW1vbnNldC9rdWJlYWRtLWt1YmVyb3V0ZXIu
    eWFtbCAtLWt1YmVjb25maWcgL2V0Yy9rdWJlcm5ldGVzL2FkbWluLmNvbmYKCiMgQmluYXJpZXMg
    ZXhwZWN0ZWQgdW5kZXIgL29wdC9jbmkvYmluIGFyZSBhY3R1YWxseSB1bmRlciAvdXNyL2xpYmV4
    ZWMvY25pCmlmIFtbICEgLWUgL29wdC9jbmkvYmluIF1dOyB0aGVuCiAgbWtkaXIgLXAgL29wdC9j
    bmkvYmluCiAgY3AgL3Vzci9saWJleGVjL2NuaS9icmlkZ2UgL29wdC9jbmkvYmluCiAgY3AgL3Vz
    ci9saWJleGVjL2NuaS9sb29wYmFjayAvb3B0L2NuaS9iaW4KICBjcCAvdXNyL2xpYmV4ZWMvY25p
    L2hvc3QtbG9jYWwgL29wdC9jbmkvYmluCmZpCgpta2RpciAtcCAvcm9vdC8ua3ViZQpjcCAtaSAv
    ZXRjL2t1YmVybmV0ZXMvYWRtaW4uY29uZiAvcm9vdC8ua3ViZS9jb25maWcKY2hvd24gJChpZCAt
    dSk6JChpZCAtZykgL3Jvb3QvLmt1YmUvY29uZmlnCkhFUkVET0MKCmJhc2ggL3Jvb3QvdXNlci1k
    YXRhLnNoID4gL3Jvb3QvdXNlci1kYXRhLmxvZ3MK
