---
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: worker-machineset
  namespace: default
  labels:
    machine.openshift.io/cluster-api-cluster: alibabacloud-actuator-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-machineset: worker-machine
      machine.openshift.io/cluster-api-cluster: alibabacloud-actuator-k8s
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-machineset: worker-machine
        machine.openshift.io/cluster-api-cluster: alibabacloud-actuator-k8s
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/compute: ""
      providerSpec:
        value:
          apiVersion: alibabacloudproviderconfig.openshift.io/v1alpha1
          kind: AlibabaCloudMachineProviderConfig
          instanceType: ecs.c6.2xlarge
          imageId:
          regionId: cn-beijing
          zoneId: cn-beijing-f
          securityGroupId:
          vpcId:
          vSwitchId:
          systemDiskCategory: cloud_essd
          systemDiskSize: 120
          internetMaxBandwidthOut: 100
          password: Hello1234
          tags:
            - key: openshift-node-group-config
              value: node-config-node
            - key: host-type
              value: node
            - key: sub-host-type
              value: default
          userDataSecret:
            name: worker-user-data-secret
          credentialsSecret:
            name: alibabacloud-credentials-secret
