---
apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  name: alibabacloud-actuator-testing-machineset
  namespace: default
  labels:
    machine.openshift.io/cluster-api-cluster: alibabacloud-actuator-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-machineset: test-worker
      machine.openshift.io/cluster-api-cluster: alibabacloud-actuator-k8s
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-machineset: test-worker
        machine.openshift.io/cluster-api-cluster: alibabacloud-actuator-k8s
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/infra: ""
      providerSpec:
        value:
          apiVersion: alibabacloudproviderconfig.openshift.io/v1alpha1
          kind: AlibabaCloudMachineProviderConfig
          instanceType: FILLIN
          imageId: FILLIN
          regionId: FILLIN
          zoneId: FILLIN
          securityGroupId: FILLIN
          vpcId: FILLIN
          vSwitchId: FILLIN
          systemDiskCategory: FILLIN
          systemDiskSize: FILLIN
          internetMaxBandwidthOut: FILLIN
          password: FILLIN
          tags:
            - key: openshift-node-group-config
              value: node-config-node
            - key: host-type
              value: node
            - key: sub-host-type
              value: default
          userDataSecret:
            name: alibabacloud-worker-user-data-secret
          credentialsSecret:
            name: alibabacloud-credentials-secret

