apiVersion: "cluster.k8s.io/v1alpha1"
kind: MachineList
items:
  - apiVersion: "cluster.k8s.io/v1alpha1"
    kind: Machine
    metadata:
      name: test1-controlplane-0
      labels:
        cluster.k8s.io/cluster-name: test1
        set: controlplane
    spec:
      versions:
        kubelet: v1.14.4
        controlPlane: v1.14.4
      providerSpec:
        value:
          apiVersion: alicloudprovider/v1alpha1
          kind: AliCloudMachineProviderSpec
          instanceType: "t2.medium"
          iamInstanceProfile: "control-plane.cluster-api-provider-alicloud.sigs.k8s.io"
          keyName: "default"
  - apiVersion: "cluster.k8s.io/v1alpha1"
    kind: Machine
    metadata:
      generateName: test1-node-
      labels:
        cluster.k8s.io/cluster-name: test1
        set: node
    spec:
      versions:
        kubelet: v1.14.4
      providerSpec:
        value:
          apiVersion: alicloudprovider/v1alpha1
          kind: AliCloudMachineProviderSpec
          instanceType: "t2.medium"
          iamInstanceProfile: "nodes.cluster-api-provider-alicloud.sigs.k8s.io"
          keyName: "default"
